apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordermanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordermanagement
  template:
    metadata:
      labels:
        app: ordermanagement
    spec:
      containers:
      - name: ordermanagement
        image: dwarakacr.azurecr.io/ordermanagement:latest
        ports:
        - containerPort: 8080